version: 2
jobs:
  test_aur:
    docker:
      - image: imrehg/archlinux-makepkg
    working_directory: ~/aur
    steps:
    - run:
        name: Update packages
        command: sudo pacman -Syu --noconfirm
    - checkout
    - run:
        name: Git clone repo
        command: |
          git clone https://aur.archlinux.org/kube-capacity.git
    - run:
        name: Testing PKGBUILD
        command: |
          cd ~/aur/kube-capacity
          namcap PKGBUILD
    - run:
        name: Building package
        command: |
          cd ~/aur/kube-capacity
          makepkg -sci --noconfirm

  release_aur:
    working_directory: ~/aur
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout

      - run:
          name: Update AUR
          command: |
            cd /tmp
            echo "aur.archlinux.org,5.9.250.164 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBOZAVWmj2k+dHTfyum7FyIivGcVUkDFHaXmPNxDwF7l8TvkAN8VDQJHEEGJhALMYtNsQ+kt0gksSh4HZqj9n5hI=" >> ~/.ssh/known_hosts
            git clone ssh://aur@aur.archlinux.org/kube-capacity.git
            cd kube-capacity
            git config user.name "Toxblh Bot"
            git config user.email "aur@palgunov.com"
            echo $(cat ~/aur/VERSION)
            sed -i "s/[0-9]\.[0-9]\.[0-9]/$(cat ~/aur/VERSION)/g" .SRCINFO
            sed -i "s/pkgver=.*/pkgver=$(cat ~/aur/VERSION)/" PKGBUILD
            git add .
            git commit -m $(cat ~/aur/VERSION)
            git push

workflows:
  version: 2
  workflow:
    jobs:
    # - test_aur
    - release_aur
